name: C Pattern Build & Run - Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GCC on Windows
        uses: Minituff/setup-gcc@v2

      - name: Compile all C files
        run: gcc main.c patterns.c -o pattern_program.exe -Wall -Wextra

      - name: Run program
        run: pattern_program.exe
